#!/bin/sh
cd "${0%/*}" || exit
#------------------------------------------------------------------------------

wclean kOmegaSSTCND/compressible
wclean kOmegaSSTCND/incompressible

rm -f foamVersionThisIsCompiledFor

#------------------------------------------------------------------------------
